name: Deploy microservice

on:
  push: 
    branches:
      - main

  workflow_dispatch: 

jobs:

  deploy:
    runs-on: ubuntu-latest
    
    env:
      VERSION: ${{ github.sha }}
      CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
      REGISTRY_UN: ${{ secrets.REGISTRY_UN }}
      REGISTRY_PW: ${{ secrets.REGISTRY_PW  }}

    steps:
      
      # Step1: Checks-out your repository under 
      - uses: actions/checkout@v3

        #Step 2: Login to Azure
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step2: Set up Terraform
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0

      # Step3: Terraform 
      - name: Terraform init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform
      
      # Step4: Builds the Docker image.
      - name: Build
        run: ./scripts/build-image.sh

      # Step5: Publishes the Docker image to the container registry.
      - name: Publish
        run: ./scripts/push-image.sh

      # Step6: Installs Kubectl and connects it to the cluster.
      - uses: azure/aks-set-context@v3
        with:
          resource-group: 'deakinuni'
          cluster-name: '${{ secrets.AKS_CLUSTER_NAME }}'
      
      #
      # Step7: Expands the configuration template and deploys the microservice.
      #
      - name: Deploy
        run: ./scripts/deploy.sh
